### PR TITLE
Fixes AdminThemeUikit - AOS Settings Page module boxes

### PR DESCRIPTION
**Pull request by gmclelland**
This fixes https://github.com/rolandtoth/AdminOnSteroids/issues/71

### CODE REVIEW

**Comment by rolandtoth** [comment]
I'll close this because I have another fix that seems to work fine but thanks for the help.

**Comment by gmclelland** [comment]
I think we might still need this.

**Comment by rolandtoth** [comment]
I cannot confirm this. Are you sure it's not cache? I've tried your fix in devtools and nothing happens. Boxes are about 75px high and I don't see if they should be less tall.

**Comment by gmclelland** [comment]
Strange...Here is what I'm seeing on Chrome on Mac with ProcessWire 3.0.80.  This is a fresh install with only AOS and TracyDebugger modules.
modules processwire pwtracy test 2017-10-26 08-40-11

What the image doesn't show is the huge blank space below the module boxes.  You have to do a lot of scrolling to see the module options.

Perhaps I'm only seeing it, because of a specific AOS enabled module with certain settings configured?

**Comment by rolandtoth** [comment]
I see now, had to upgrade to the latest uikit theme (and pw). Will fix later today.

**Pull request closed without merging**
